import {
  FileUIPart,
  ModelMessage,
  streamText,
  TextUIPart,
  generateText,
} from "ai";
import { APIOptions, ChatMessage } from "../type";
import { ValidationError } from "../errors";

export const systemInstruction = `
# ROLE & IDENTITY
You are the official **CTU 60th Anniversary AI Assistant**, representing Can Tho University (1966-2026). Your tone is professional, welcoming, and celebratory. 

# LANGUAGE & REASONING LOGIC
- **Linguistic Parity:** You must think and respond in the same language the user uses. If the query is in Vietnamese, your reasoning and final answer MUST be in Vietnamese.
- **Natural Response:** Do not use labels like "Thought:", "Action:", or "Response:". Provide a direct, conversational response. Note: Your internal reasoning process will be visible to the user, so keep it logical and in the correct language.

# OPERATIONAL GUIDELINES
- **Factual Accuracy:** Your primary source of truth is the **Retrieval Tool**. Use it for ALL specific dates, names of leaders, and historical milestones.
- **Historical Nuance:** Be precise with titles (e.g., distinguishing between 'Viện trưởng' of the founding era and 'Hiệu trưởng' of the later era). 
- **No Hallucination:** If the tool does not provide specific data, admit it and refer to the official website: https://www.ctu.edu.vn
- **Scope:** Focus on the 60-year legacy. For current administrative tasks (tuition, grades, portal help), politely redirect to the relevant department.

# INTERACTION STYLE
- Use evocative and proud language.
- Keep responses concise but informative.
- Ensure the user feels the significance of the 60th-anniversary milestone.

---

## Examples of Natural Interaction

**User (Vietnamese):** "Ai là Hiệu trưởng đầu tiên của Đại học Cần Thơ?"
**Assistant:** "Để thông tin đến bạn một cách chính xác nhất về lịch sử nhà trường: ông Phạm Sơn Khai là vị Hiệu trưởng đầu tiên của Trường Đại học Cần Thơ. Trước đó, trong giai đoạn mới thành lập năm 1966 (thời kỳ Viện Đại học Cần Thơ), Giáo sư Phạm Hoàng Hộ giữ chức vụ Viện trưởng. Đây đều là những người thầy vĩ đại đã đặt nền móng vững chắc cho hành trình 60 năm phát triển của chúng ta."

**User (English):** "What happened in 1966 at CTU?"
**Assistant:** "1966 was the pivotal year when the University of Can Tho (Viện Đại học Cần Thơ) was officially established. It began with four faculty groups: Sciences, Law and Social Sciences, Letters, and Education. This founding moment began our 60-year mission of 'Lighting up knowledge' in the Mekong Delta."

**User (Vietnamese):** "Làm sao để tôi xem kết quả học tập?"
**Assistant:** "Chào bạn! Với vai trò là Trợ lý AI Kỷ niệm 60 năm, tôi rất sẵn lòng chia sẻ về lịch sử hào hùng và các hoạt động lễ hội của trường. Tuy nhiên, để xem kết quả học tập cá nhân, bạn vui lòng truy cập Hệ thống Quản lý Sinh viên hoặc liên hệ Phòng Đào tạo để được hỗ trợ chính xác nhất nhé!"
`;

export interface Chatbot {
  convertUIMessages(messages: ChatMessage[]): Promise<ModelMessage[]>;
  streamText(
    messages: ChatMessage[],
    options?: APIOptions,
  ): Promise<ReturnType<typeof streamText>>;

  generateText(
    messages: ChatMessage[],
    options?: APIOptions,
  ): Promise<ReturnType<typeof generateText>>;
}

export class ChatMessageUtils {
  /**
   * Validates a text UI part to ensure it contains non-empty text.
   *
   * This method checks if the provided `textPart` object exists and if its
   * `text` property contains non-whitespace characters.
   *
   * @param textPart - The text UI part object to validate.
   * @returns The original `textPart` object if validation succeeds.
   * @throws {ValidationError} Throws an error if `textPart` is null/undefined
   * or if the text content is empty or whitespace only.
   */
  static validateTextPart(textPart?: TextUIPart) {
    if (!textPart || textPart.text.trim().length === 0)
      throw new ValidationError("No text prompt found.");
    return textPart;
  }

  /**
   * Searches backward through an array of chat messages to find the last file
   * part generated by the 'assistant' role that matches a specific MIME type.
   *
   * This function uses `messages.toReversed()` (available in modern environments)
   * to efficiently start the search from the end of the conversation (the most recent messages).
   * It returns the first matching file part it encounters, which corresponds to
   * the **most recently generated file** by the assistant matching the criteria.
   *
   * @param messages The array of ChatMessage objects to search through, ordered chronologically.
   * @param mimeType The MIME type string (or a substring) to match against the file's mediaType (e.g., 'image/', 'audio/mpeg', or just 'video').
   * @returns The last (most recent) matching FileUIPart object found, or `null` if no matching file part is found.
   */
  static findLastGeneratedFile(messages: ChatMessage[], mimeType: string) {
    const reversedMsgs = messages.toReversed();
    for (const msg of reversedMsgs) {
      if (msg.role !== "assistant") continue;
      const imgPart = msg.parts.find(
        (part) => part.type === "file" && part.mediaType.includes(mimeType),
      );
      if (imgPart) return imgPart as FileUIPart;
    }
    return null;
  }
  /**
   * Finds and extracts the content of the last message sent by the `user` role
   * in a conversation history.
   *
   * This function specifically extracts the *first* text part and the *first* image
   * file part from the last user message. It ignores all other parts (like audio,
   * video, or additional text/image parts within that message).
   *
   * @param messages The array of ChatMessage objects representing the conversation history.
   * @returns An object containing the extracted prompt details:
   * - `text`: The trimmed string content of the first text part, or `undefined`.
   * - `userImage`: The URL string of the first image file part, or `undefined`.
   * Returns `null` if no message with the role `user` is found in the array.
   */
  static findLastUserPrompt(messages: ChatMessage[]) {
    let prompt: { text?: string; userImage?: string } = {};
    const userMessage = messages.findLast((msg) => msg.role === "user");
    if (userMessage === undefined) return null;

    for (const part of userMessage.parts) {
      switch (part.type) {
        case "text": {
          if (prompt.text === undefined)
            prompt = { ...prompt, text: part.text.trim() }; // Use the first text part only
          break;
        }
        case "file": {
          if (
            part.mediaType.includes("image/") &&
            prompt.userImage === undefined
          ) {
            prompt = {
              ...prompt,
              userImage: part.url,
            }; // Use the first image only
          }
          break;
        }
        default:
          break;
      }
    }

    return prompt;
  }

  static getFilePartsByMIME(message: ChatMessage, mime: string) {
    return message.parts.filter(
      (part) => part.type === "file" && part.mediaType.includes(mime),
    ) as FileUIPart[];
  }
}
